name: build and deploy

on:
  push:
    branches:
      - source
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: working dir
        run: |
          pwd
          ls -la
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: test
        run: |
          pwd
          ls -la
          npm install 